Vagrant.configure("2") do |config|

    config.vm.box = "debian/stretch64"
  
    ############################################################
    # Base Provision
  
    # Update and Upgrade Packages
    config.vm.provision :shell, inline: "apt-get update -y"
    config.vm.provision :shell, inline: "apt-get upgrade -y --autoremove"
  
    # Install git Prerequisites 
    config.vm.provision :shell, inline: "apt-get -y install git zsh curl vim"
  
    # Clone Oh My Zsh from the git repo
    config.vm.provision :shell, privileged: false,
        inline: "git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh"
  
    # Copy in the default .zshrc config file
    config.vm.provision :shell, privileged: false,
        inline: "cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc"
  
    # Change the vagrant user's shell to use zsh
    config.vm.provision :shell, inline: "chsh -s /bin/zsh vagrant"
  
    ############################################################
  
    config.vm.define "nodejs-env"

    config.vm.synced_folder "./app", "/home/vagrant/app"
  
    config.vm.network "private_network", ip: "192.168.10.10"
  
    config.vm.provision "shell", path: "bootstrap.sh"
  
    config.vm.provider "virtualbox" do |vb|
        vb.name = "nodejs-env-box"
        vb.cpus = 2
        vb.memory = "2048"
        vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
    end
  
  end
  